### ISSUE TITLE
wish transfer displayed in accounts

### ISSUE THREAD

**Issue by Beadsley** [sdastarks/My-Budget#121]

**Comment by Beadsley** [comment]
* make sure the wish transfer shown in the accounts activity is visible
* constrain the length of the wish name

**Comment by Beadsley** [comment]
*  addChoresMoneyFragment (chores title)
* New wish fragment (wish title)
* Edit Wish fragment (wish title)
* Inflow Outflow Fragment (description)

**Comment by AnastasijaGurejeva** [comment]
Fixed in 121 commit
